### ISSUE TITLE
Changes to conform with Shelf standards

### ISSUE THREAD

**Issue by quantumew** [not-nexus/shelf-lib-js#2]
I am using your library for Columbo and while using it I noticed two things that before this is released should be added to conform with Shelf.

- Not having to send sort or search criteria (perhaps make the criteria/params an object)
- Being able to limit search results (Shelf does this for you so you can just pass the criteria along)

That is all I found while doing my basic operations with your library that are a necessity to me that aren't there. Thanks!

**Comment by GoogilyBoogily** [comment]
Fixed in pull request #3
